### ISSUE TITLE
Space in library path

### ISSUE THREAD

**Issue by nico-robert** [apnadkarni/tcl-cffi#130]
**Describe the bug**
When there are spaces in library path, package `cffi` fail.

**To Reproduce**
```
lappend auto_path {C:\Users\Nicolas ROBERT\AppData\04-appli\lib}
package require cffi
```
Error :
_attempt to provide package cffi 1.0.7 failed: no version of package cffi provided
    ("package ifneeded cffi 1.0.7" script)
    invoked from within
"package require cffi"_

**Environment:**
 - Architecture: x86_64
 - OS and version: Windows 10
 - Tcl version: 8.6
 - CFFI version: 1.0.7

**Additional context**
I have made a change in the `pkgIndex.tcl` file :
```
# ...
set path [list [file join $dir $dllname]] ;  # add list
set path [list [file join $dir $platform $dllname]]  ;  # add list
# ...
```

**Comment by apnadkarni** [comment]
I don't think this is a bug in cffi. Iirc auto_path requires forward slashes even on Windows. Can you please try changing the backslashes in the lappend auto_path to forward slashes and see if that works (without your other change to pkgIndex.tcl).

**Comment by nico-robert** [comment]
same behavior. I’d rather be on a problem with `load` command.
```
lappend auto_path "C:/Users/Nicolas ROBERT/AppData/04-appli/lib"
# {C:/Users/Nicolas ROBERT/AppData/04-appli/bin/tclkitsh.exe/lib/tcl8.6} {C:/Users/Nicolas ROBERT/AppData/04-appli/bin/tclkitsh.exe/lib} {C:/Users/Nicolas ROBERT/AppData/04-appli/lib}
```

**Comment by apnadkarni** [comment]
OK, thanks, I'll take a closer look.

Are you starting a new package by any chance? Just curious. I saw you ticklecharts, looks very nice.

**Comment by apnadkarni** [comment]
Indeed, at first glance the load command seems to need a [list ] wrapper because of the uplevel.

**Comment by nico-robert** [comment]
> Are you starting a new package by any chance? Just curious.

Yeah, [cimgui](https://github.com/cimgui/cimgui) , but I think I’m trying to climb "Everest" without training :wink:.
I’m just getting started, I probably have questions to see if it's possible , l'will go in this section [tcl-cffi Discussions](https://github.com/apnadkarni/tcl-cffi/discussions)
>  I saw you ticklecharts, looks very nice.

Thanks
