### ISSUE TITLE
cffi 2.0b1 does not compile on Windows using gcc and Tcl 9

### ISSUE THREAD

**Issue by PaulObermeier** [apnadkarni/tcl-cffi#204]
cffi does not compile on Windows using gcc and Tcl 9, because it searches libtommath in wrong (cffi) directory.

When changing the line in files configure.ac resp. configure, cffi compiles.

Change:
    TCL_TOMMATH_LIB=\${libdir}/${TCL_TOMMATH_LIB_NAME}
to:
    TCL_TOMMATH_LIB=${TCL_EXEC_PREFIX}/lib/${TCL_TOMMATH_LIB_NAME}

Running test suite generates lots of errors (but the failures are the same as for 8.6.15):

all.tcl:        Total   11476   Passed  11245   Skipped 45      Failed  186
Sourced 16 Test Files.
Files with failing tests: arena.test callback.test function.test interface.test memory.test pointer.test prototype.test struct.test type.test union.test varargs.test
Number of tests skipped for each constraint:
        13      !structbyval
        3       !structbyval packsupport
        2       !win
        1       disabled
        25      dyncall
        1       win32

**Comment by apnadkarni** [comment]
What version of gcc and mingw is this ? Github [MingW CI](https://github.com/apnadkarni/tcl-cffi/actions/runs/11138803884)  shows no errors. I am admittedly somewhat confused by tommath in Tcl 9. As per my understanding it is possible to link against the system tommath library directly or via Tcl stubs. Could the error have something to do with how Tcl was built?

Regarding the failing tests, what version of libffi? Min required is 3.4.4 because of stack corruption bugs in libffi. Just want to make sure not chasing 

/Ashok

**Comment by PaulObermeier** [comment]
Here is my mingw environment, the configuration of Tcl and cffi and the test suite output:
Windows 11, gcc 7.2.0, libffi 3.4.6
uname -r: 3.0.7-338

Tcl configuration:
> LDFLAGS=' -s ' /C/BawtBuilds/TclDistribution/TclDistribution-9.0.0-9.0.0/Windows/x64/Release/Build/Tcl/win/configure
                 --build=x86_64-w64-mingw32
                 --prefix=/C/BawtBuilds/TclDistribution/TclDistribution-9.0.0-9.0.0/Windows/x64/Release/Install/Tcl
                 --exec-prefix=/C/BawtBuilds/TclDistribution/TclDistribution-9.0.0-9.0.0/Windows/x64/Release/Install/Tcl
                 --enable-64bit
                 --disable-symbols

cffi configuration:
> CFLAGS='-IC:/BawtBuilds/TclDistribution/TclDistribution-9.0.0-9.0.0/Windows/x64/Development/include' LDFLAGS=-'LC:/BawtBuilds/TclDistribution/TclDistribution-9.0.0-9.0.0/Windows/x64/Development/lib' LIBFFI_LIBS=-llibffi /C/BawtBuilds/TclDistribution/TclDistribution-9.0.0-9.0.0/Windows/x64/Release/Build/cffi/configure
                 --enable-shared
                 --enable-threads
                 --prefix=/C/BawtBuilds/TclDistribution/TclDistribution-9.0.0-9.0.0/Windows/x64/Release/Install/cffi
                 --exec-prefix=/C/BawtBuilds/TclDistribution/TclDistribution-9.0.0-9.0.0/Windows/x64/Release/Install/cffi
                 --with-tcl=/C/BawtBuilds/TclDistribution/TclDistribution-9.0.0-9.0.0/Windows/x64/Release/Build/Tcl
                 --with-tk=/C/BawtBuilds/TclDistribution/TclDistribution-9.0.0-9.0.0/Windows/x64/Release/Build/Tk
                 --build=x86_64-w64-mingw32
                 --enable-64bit
                 --disable-symbols
                 --disable-staticffi

[all.txt](https://github.com/user-attachments/files/17249989/all.txt)

**Comment by apnadkarni** [comment]
The failing tests indicate it is not a libffi issue, I don't think. They all seem to have to do with pointers being NULL or function pointers not in executable page (ignoring the errors pertaining to German error messages). 

I tested with gcc 9.4, 11.3 and 13.2  but I cannot imagine how gcc 7 would behave differently. Consider the very simple test pointer-isnull-2

```
        cffi::pointer isnull [makeptr 1]
```

This is returning 1 on your build when it should be 0. The test failures indicate all pointers are being seen as NULL.
That gives me hint where to look. Can you print the output of the following using the same compiler tool chain as above?

```
#include <stdio.h>
int main()
{
    void *pv = &pv;
   int i = sscanf("0x1^", "%p^", &pv);
   printf("%d, %p", i, pv);
    return 0;
}
```

I get the following with my gcc toolchain:

```
1, 0000000000000001
```

I suspect you will get

```
1, 0000000000000000
```

which would indicate different sscanf %p implementation in the C runtime.

**Comment by PaulObermeier** [comment]
Your sscanf idea was correct. I tested on various systems and compilers and it seems to be a Windows-only problem with older compilers (both gcc and VS):

MinGW gcc
=========

gcc 7.2.0 (64-bit)
1, 0000000000000000

gcc 7.2.0 (32-bit)
1, 00000000

gcc 8.1.0 (64-bit)
1, 0000000000000000

gcc 11.2.0 (64-bit)
1, 0000000000000001

gcc 12.2.0 (64-bit)
1, 0000000000000001

gcc 13.2.0 (64-bit)
1, 0000000000000001

gcc 14.2.0 (64-bit)
1, 0000000000000001

Visual Studio
=============

_MSC_VER 1500 (32-bit) VS2008
1, 00000000

_MSC_VER 1600 (32-bit) VS2010
1, 00000000

_MSC_VER 1800 (64-bit) VS2013
1, 0000000000000000

_MSC_VER 1900 (64-bit) VS2015
1, 0000000000000001

_MSC_VER 1916 (64-bit) VS2017
1, 0000000000000001

_MSC_VER 1929 (64-bit) VS2019
1, 0000000000000001

_MSC_VER 1941 (64-bit) VS2022
1, 0000000000000001

Linux gcc versions
==================

gcc 4.8.1 (32-bit)
1, 0x1

gcc 4.8.5 (64-bit)
1, 0x1

gcc 4.9.2 (64-bit)
1, 0x1

gcc 7.5.0 (64-bit)
1, 0x1

gcc 9.4.0 (64-bit)
1, 0x1

gcc 12.2.0 (64-bit)
1, 0x1

gcc 13.2.0 (64-bit)
1, 0x1

gcc 14.2.0 (64-bit)
1, 0x1

gcc 14.2.1 (64-bit)
1, 0x1

MacOS
=====

gcc 4.2.1 (64-bit)
clang 16.0.0 (clang-1600.0.26.3) (64-bit)
1, 0x1

**Comment by PaulObermeier** [comment]
With current trunk all tests succeed on Windows using gcc 7.2.0.
Expect 24 tests using German output messages, which are equivalent to the English messages.

**Comment by apnadkarni** [comment]
Thanks, closing.
