### ISSUE TITLE
cffi 2.0b1 does not link on MacOS

### ISSUE THREAD

**Issue by PaulObermeier** [apnadkarni/tcl-cffi#207]
On MacOS Sonoma 14.7 (M2) the sources are compiled, but the linker cannot find libuuid.
This seems to be a configure problem, as include file "uuid/uuid.h" is existent.
Maybe a Mac expert can help (ex. one has to specifiy a specific MacOS framework?).

There is 1 warning on MacOS, which may be an error in future compiler versions:
./generic/tclCffiCallback.c:412:39: warning: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
  412 |     return subCommands[cmdIndex].cmdFn(ipCtxP, ip, objc, objv);

Adding a signature to the definition of cmdFn eliminates the warning:
typedef struct Tclh_SubCommand {
    const char *cmdName;
    int minargs;
    int maxargs;
    const char *message;
    int (*cmdFn)(CffiInterpCtx *ipCtxP,
                   Tcl_Interp *ip,
                   int objc,
                   Tcl_Obj *const objv[]);
    int flags; /* Command specific usage */
} Tclh_SubCommand;

**Comment by apnadkarni** [comment]
Fixed by removing uuid dependency. Added github runners for macos-12,13,14. Verified there.

**Comment by apnadkarni** [comment]
Forgot to mention. The cmdFn warnings will stay as they are. Sticking to C99 as those functions are polymorphic with differing signatures.

**Comment by PaulObermeier** [comment]
Builds fine on Sonoma. All tests succeeded.
