### ISSUE TITLE
Include tclh sources in zip and tar.gz download files

### ISSUE THREAD

**Issue by PaulObermeier** [apnadkarni/tcl-cffi#208]
The current download files cannot be used out of the box because of missing tclh sources.
It would be nice to have tclh included in these distribution files.

**Comment by apnadkarni** [comment]
Paul, just checked and the 2.4.b1 downloads from sourceforge do contain the tclh sources.

**Comment by PaulObermeier** [comment]
I used the downloads from github. Those have an empty tclh directory.
The downloads from SourceForge indeed contain the tclh sources.

BTW: File name 2.4b1 is wrong. The release is 2.0b1.

**Comment by apnadkarni** [comment]
Thanks for the filename correction. Just rushing through multiple extensions and got the version numbers confused.

The github downloads are automatically generated and there is no way I can see to include git submodules (tclh) there, nor a way to stop github from generating these "pseudo releases".
