### ISSUE TITLE
Access to requested resource is denied on AWS

### ISSUE THREAD

**Issue by rishav2898** [apnadkarni/tcl-cffi#50]
** I am trying to hit the amazon SP-API endpoint. When I am hitting the API endpoint, I am always getting an error 403 Forbidden with the message Access to the requested resource is denied.**

{
    "errors": [
        {
            "message": "Access to requested resource is denied.",
            "code": "Unauthorized",
            "details": ""
        }
    ]
}

step I did
I have created the IAM user, IAM role, and IAM policies.
I have created the seller account and developer account as well.
I am using the role ARN in my seller central app.
Using the access token to sign the API request.

**Comment by apnadkarni** [comment]
It is not clear to me what this has to do with cffi. Are you using cffi to access some API? If so which specific API and how have you defined the cffi interface to it? Please understand that CFFI provides access to arbitrary API's and I cannot answer questions about those API's themselves (most likely I do not even know them), only about the CFFI definitions. It's like asking the Visual Studio compiler folks why your call is failing.

If you think CFFI is the issue please state clearly what the C API prototype looks like, and your CFFI declaration for that C prototype.

**Comment by apnadkarni** [comment]
Closing as no response from OP.
