### ISSUE TITLE
'NULL' pointer

### ISSUE THREAD

**Issue by nico-robert** [apnadkarni/tcl-cffi#63]
Hello @apnadkarni ,
I try to pass a null pointer as parameter in my function. 
```
cffi::alias define MY_POINTER pointer.int
LIB stdcall GetRoot pointer.int {h {MY_POINTER nullifempty} value float}
# tcl code :
set root [GetRoot "" 10]
```
I'm getting an error :
_Invalid value "MY_POINTER nullifempty". A type annotation is not valid for the data type._

I don't know if it's possible... or if it exists

my C function will be like this : 
`root = GetRoot (NULL, 10);`

Thanks 
Nicolas

**Comment by apnadkarni** [comment]
`nullifempty` is only for strings (a way to pass NULL for string parameters where that is accepted). 

For NULL pointers, pass "0^" or "0^int".

So something like,
```
cffi::alias define MY_POINTER pointer.int
LIB stdcall GetRoot pointer.int {h MY_POINTER value float}
# tcl code :
set root [GetRoot 0^ 10]
```
I just realized passing NULL pointers is not documented anywhere.

/Ashok

**Comment by apnadkarni** [comment]
BTW, comments and issues on using cffi always appreciated. Nothing like real world user feedback to know what is missing/broken etc. and to prioritize.

**Comment by apnadkarni** [comment]
From 1.0a8 onward, just plain `0` is accepted as a null pointer.

**Comment by nico-robert** [comment]
Thanks , it's works... with `0^int`.
It’s a pity that `null` or `nothing` is not accepted too (personal opinion...), I find these 2 words more telling than just the value "0" but it is true that these 2 words are not familiar in the language Tcl 

Regards
Nicolas

**Comment by apnadkarni** [comment]
Changed to accept NULL (upper case to match C convention) but not just 0 (decided to not confuse integer syntax).
