### ISSUE TITLE
Comments inside 'stdcalls'

### ISSUE THREAD

**Issue by nico-robert** [apnadkarni/tcl-cffi#71]
Hello @apnadkarni ,
It would be nice if we had the opportunity to comment on the code inside `stdcalls`...
Like this :
```
LIB stdcalls {
    # comment function
    FUNCTION1 void {}

    # comment function
    FUNCTION2 void {}
}
```
Thanks
Nicolas

**Comment by apnadkarni** [comment]
For now I would prefer to leave the cffi calls bare bones and just leave it to the user to layer a preprocessor. For example, your requests for comments could be done something like (not tested)

````
proc my_stdcalls {lib calldefs} {
   # Strip comment lines before calling stdcalls
   set calldefs [join [lmap line [split $calldefs \n] {
      if {[regexp {^\s*#} $line]} continue
      set line
   }] \n]
   $lib stdcalls $calldefs
}
````

**Comment by nico-robert** [comment]
Ok , I understand 
Thanks anyway

Regards
Nicolas
